name: "Tweet on PR Action"
description: "Send a celebratory tweet when someone creates a PR"
author: "Jessica Greene"
inputs:
  consumer-key:
    description: >
      Consumer API key, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  consumer-secret:
    description: >
      Consumer API secret key, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  access-token:
    description: >
      Application access token, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  access-token-secret:
    description: >
      Application access token secret, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
outputs:
  status:
    description: "Status of whether tweet was sent"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'message-square'
  color: yellow