name: example
on: pull_request
jobs:
  comment:
    name: Add checkout and pull commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sleepypioneer/actions_to_celebrate@further-fixes
        with:
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}